### ISSUE TITLE
Parsing date with trailing punctation fails with 0.15.0

### ISSUE THREAD

**Issue by charlax** [crsmithdev/arrow#661] opened 2019-09-10 09:03 UTC
This is pretty simple to reproduce.

Parsing a date with trailing punctuation (e.g. `"11 juillet 2018."`) works find with v0.14.7:

```
In [2]: import arrow

In [3]: arrow.get("11 juillet 2018.", "D MMMM YYYY", locale="fr_FR")
Out[3]: <Arrow [2018-07-11T00:00:00+00:00]>
```

and fails with 0.15.0:

```
>>> import arrow
>>> arrow.get("11 juillet 2018.", "D MMMM YYYY", locale="fr_FR")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "virtualenvs/arrow-11XYHcdu/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "virtualenvs/arrow-11XYHcdu/lib/python3.7/site-packages/arrow/factory.py", line 230, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "virtualenvs/arrow-11XYHcdu/lib/python3.7/site-packages/arrow/parser.py", line 216, in parse
    "Failed to match '{}' when parsing '{}'".format(fmt, datetime_string)
arrow.parser.ParserMatchError: Failed to match 'D MMMM YYYY' when parsing '11 juillet 2018.'
```

Since it's not mentioned in the CHANGELOG as a breaking change, I presume it's a bug? The CHANGELOG does mention a change about handling trailing whitespace.

**Comment by systemcatch** [comment] 2019-09-10 09:54
As far as I can tell this is expected behaviour at the moment. 

> Since it's not mentioned in the CHANGELOG as a breaking change, I presume it's a bug?

The changelog for 0.15.0 was difficult to write because the biggest changes were to do with the tokens themselves. Many things like this would fall under preventing partial matches so aren't listed individually.

**Comment by charlax** [comment] 2019-09-10 16:52
I think it'd be really helpful to document those cases because some other people might be expecting the pre-v0.15 behavior. Also, the CHANGELOG only links to a bunch of issues without necessarily clarifying: a casual reader might completely miss that.

I totally understand breaking changes, but properly documenting makes them much easier to accept and alleviate. I'd be happy to take a stab at documenting it.

**Comment by systemcatch** [comment] 2019-09-11 10:12
@charlax Sure feel free to do that. I don't expect that any future release of arrow will have this many breaking changes again (famous last words!).

**Comment by jadchaar** [comment] 2019-09-11 16:04
I agree with @systemcatch. v0.15.0 was meant to be a revamp of the parsing engine for Arrow to fix many fundamental bugs that have plagued the library for years. After this release, breaking changes should be rare outside of deprecations.

**Comment by jadchaar** [comment] 2019-09-14 15:46
Hey @charlax, if you'd like to clean up the documentation, feel free to, but I am going to close this issue for now since this change to parsing behavior was intentional :).

**Closed by jadchaar** 2019-09-14 15:46 UTC
Labels: documentation
