### ISSUE TITLE
in-correct output for nano-second precision

### ISSUE THREAD

**Issue by goldenbull** [crsmithdev/arrow#398] opened 2016-12-20 09:01 UTC
source code:
```python
import arrow

dt = arrow.get("2016-12-31 12:34:56.123456")
print(dt)
print(dt.format("YYYY-MM-DD HH:mm:ss.SSSSSSSSSSSS"))
```

output:
```
2016-12-31T12:34:56.123456+00:00
2016-12-31 12:34:56.123456123456
```

If user specifies the output precision more than 6 'S', the output string should be zero's, or an Exception could be raised

**Comment by andrewelkins** [comment] 2016-12-31 21:37
Confirmed. It's likely linked to #341

**Comment by andrewelkins** [comment] 2016-12-31 22:41
Duplicate of #324

**Closed by andrewelkins** 2016-12-31 22:41 UTC
Labels: bug
