### ISSUE TITLE
tzinfo is ignored in arrow.get() with time string

### ISSUE THREAD

**Issue by kkroening** [crsmithdev/arrow#515] opened 2018-01-29 23:12 UTC
The `tzinfo` parameter doesn't seem to do anything when calling `arrow.get`, at least with a time string in the form of `YYYY-MM-DD mm:ss`:
```
In: arrow.get('2018-01-29 14:46', tzinfo='US/Central')
Out: <Arrow [2018-01-29T14:46:00+00:00]>

In: arrow.get('2018-01-29 14:46', tzinfo=pytz.timezone('US/Central'))
Out: <Arrow [2018-01-29T14:46:00+00:00]>
```

The constructed arrow ends up with the wrong timezone (utc) as shown above.

Is there another way to do this?  Or at least a way to replace the timezone of the arrow object without affecting the time? This workaround does the job, but kinda defeats the purpose of using `arrow`:
```
In: arrow.get(pytz.timezone('US/Central').localize(arrow.get('2018-01-29 14:46').datetime.replace(tzinfo=None)))
Out: <Arrow [2018-01-29T14:46:00-06:00]>
```

**Comment by kkroening** [comment] 2018-01-29 23:19
Also note that the kwargs don't seem to be sanity-checked either:
```
In: arrow.get('2018-01-29 14:46', some_crazy_kwarg='foobar')
Out: <Arrow [2018-01-29T14:46:00+00:00]>
```

**Comment by agosto-karlkroening** [comment] 2018-01-30 01:36
Probably a duplicate of #493.

**Closed** 2018-03-11 18:09 UTC
