### ISSUE TITLE
.get fails to parse

### ISSUE THREAD

**Issue by offby1** [crsmithdev/arrow#168] opened 2014-10-07 20:28 UTC
I am not absolutely certain that this should work, but `time.strptime` seems to have no trouble, so it surprised me that arrow didn't work:

```
>>> import arrow
>>> import time
>>> stamp = '17:24:02 UTC Wed Aug 27 2014'
>>> format = '%H:%M:%S %Z %a %b %d %Y'
>>> time.strptime(stamp, format)
time.struct_time(tm_year=2014, tm_mon=8, tm_mday=27, tm_hour=17, tm_min=24, tm_sec=2, tm_wday=2, tm_yday=239, tm_isdst=0)
>>> arrow.get(stamp, format)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/arrow/factory.py", line 186, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/arrow/parser.py", line 135, in parse
    raise ParserError('Failed to match token \'{0}\' when parsing \'{1}\''.format(token, original_string))
arrow.parser.ParserError: Failed to match token 'a' when parsing '17:24:02 UTC Wed Aug 27 2014'
>>> 
```

**Comment by andrewelkins** [comment] 2015-02-27 21:52
This does not seem to be intentional, nor expected. Marking as a bug.

**Comment by lumitim** [comment] 2015-04-07 16:23
This seems to be related; I believe that `.get` is using the arrow time formatting even when given than strptime formats. Note the mixup between month and minute.
```In [3]: arrow.get('12/1/2015', '%m/%d/%Y')
Out[3]: <Arrow [0001-01-01T00:12:00+00:00]>

In [4]: arrow.get('12/1/2015', '%M/%d/%Y')
Out[4]: <Arrow [0001-12-01T00:00:00+00:00]>
```

**Comment by mlew** [comment] 2015-08-09 04:56
+1 - This seems to be behaving exactly as intended.  Out of curiosity, what's the motivation for `arrow` to have a separate set of parsing tokens from the standard Python tokens?

**Comment by offby1** [comment] 2015-08-09 18:49
I only _just now_ realized that Arrow might recognize a different
"language" than strptime. That's OK, I guess (if Arrow's language is
clearly better), but it's certainly surprising ... It'd help if the
documentation had a warning in large flashing neon letters saying "Warning!
These tokens are _different_ than strptime's!"

**Closed** 2018-12-14 17:37 UTC
Labels: bug
